import React, { ReactNode } from 'react';
import { Header } from './Header';
import Head from 'next/head';
import {ResponsiveAppBar} from './NavBar';

interface LayoutProps {
  children: ReactNode;
}

export const Layout: React.FC<LayoutProps> = ({ children }) => {
  const [backgroundImage, setBackgroundImage] = React.useState<string | null>(null);

  return (
    <>
      <Head>
        <title>SUSHIFLIX</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ResponsiveAppBar backgroundImage={backgroundImage} />
      {children}
    </>
  );
};